### DISCUSSION TITLE
show total real time generation for 2 inverters in 1

### DISCUSSION THREAD

**Discussion by chesterflaps** [macxq/foxess-ha#193] [Q&A]
Hi.

I have created a sensor to show me the total generated power for the day across 2 inverters and it works just fine.

The issue I have is with doing the same for real time generation.

Here is the code for the one that works

```
- sensor:
    - name: power_solar_total_today
      unique_id: "power_solar_total_today"
      state: "{{ states('sensor.foxess1_energy_generated') |int(0) + states('sensor.foxess2_energy_generated') |int(0) }}"
      unit_of_measurement: "kWh"
      device_class: energy
      state_class: total_increasing
```

Here is the one that does not work. I have tried a few different entities and I have either got unlucky and not found the correct one or there is something else wrong.

```
- sensor:
    - name: power_solar_actual_today
      unique_id: "power_solar_actual_today"
      state: "{{ states('sensor.foxess1_solar_power') |int(0) + states('sensor.foxess2_solar_power') |int(0) }}"
      unit_of_measurement: "kWh"
      device_class: energy
      state_class: total_increasing
```
