### DISCUSSION TITLE
Sample Sensors for better Solar Monitoring

### DISCUSSION THREAD

**Discussion by Phoenix17785** [macxq/foxess-ha#218] [Q&A]
Don't I need something in this code added if I have 3 inverters? 

For me as a beginner the code looks like it's for 2 inverters.

``
# Setup Better Solar Tracking Sensors that resolve negative solar tracking  

  - platform: integration
    source: sensor.foxess_pv1_power
    name: pv1_sum
    unit_time: h
    round: 2
  - platform: integration
    source: sensor.foxess_pv2_power
    name: pv2_sum
    unit_time: h
    round: 2
    
# Setup Daily and real-time solar trackers that resolve the negative solar tracking    

utility_meter:
    daily_pv1_sum:
        source: sensor.pv1_sum
        cycle: daily
 
    daily_pv2_sum:
        source: sensor.pv2_sum
        cycle: daily
        
# Setup Daily and real-time solar trackers that resolve the negative solar tracking   
       
template:
  - sensor:
      - name: "Solar Power Daily"
        unit_of_measurement: "kWh"
        state: "{{ states('sensor.daily_pv1_sum') | float + states('sensor.daily_pv2_sum') | float }}"
 
      - name: "Solar Power Now"
        unit_of_measurement: "kW"
        state: "{{ states('sensor.foxess_pv1_power') | float + states('sensor.foxess_pv2_power') | float }}"
``

**Comment by FozzieUK** [comment]
Yes this code is actually for a single inverter (with 2 strings PV1 & PV2) which is what most users have.

For your 3 inverters you would need to replicate this but with the different entity names from each inverter.

Find the PV1 name for each of your inverters (it will be something like sensor.xxxxxxx_pv1_power ) where xxxxxxx is each inverter name, repeat that for PV2

then duplicate the code in your configuration.yaml for each inverter

As an example - for inverter names of  'inverter1', 'inverter2', 'inverter3'

You would have sensor names of:-
sensor.inverter1_pv1_power
sensor.inverter2_pv1_power
sensor.inverter3_pv1_power

sensor.inverter1_pv2_power
sensor.inverter2_pv2_power
sensor.inverter3_pv2_power

So then this code would become -

```
# Setup Better Solar Tracking Sensors that resolve negative solar tracking  

  - platform: integration
    source: sensor.inverter1_pv1_power
    name: pv1_inverter1_sum
    unit_time: h
    round: 2
  - platform: integration
    source: sensor.inverter2_pv1_power
    name: pv1_inverter2_sum
    unit_time: h
    round: 2
  - platform: integration
    source: sensor.inverter3_pv1_power
    name: pv1_inverter3_sum
    unit_time: h
    round: 2

  - platform: integration
    source: sensor.inverter1_pv2_power
    name: pv2_inverter1_sum
    unit_time: h
    round: 2
  - platform: integration
    source: sensor.inverter2_pv2_power
    name: pv2_inverter2_sum
    unit_time: h
    round: 2
  - platform: integration
    source: sensor.inverter3_pv2_power
    name: pv2_inverter3_sum
    unit_time: h
    round: 2

    
# Setup Daily and real-time solar trackers that resolve the negative solar tracking    

utility_meter:
    daily_pv1_inverter1_sum:
        source: pv1_inverter1_sum
        cycle: daily
    daily_pv1_inverter2_sum:
        source: pv1_inverter2_sum
        cycle: daily
    daily_pv1_inverter3_sum:
        source: pv1_inverter3_sum
        cycle: daily
 
    daily_pv2_inverter1_sum:
        source: sensor.pv2_inverter1_sum
        cycle: daily
    daily_pv2_inverter2_sum:
        source: sensor.pv2_inverter2_sum
        cycle: daily
    daily_pv2_inverter3_sum:
        source: sensor.pv2_inverter3_sum
        cycle: daily

# Setup Daily and real-time solar trackers that resolve the negative solar tracking   
       
template:
  - sensor:
      - name: "Inverter 1 Solar Power Daily"
        unit_of_measurement: "kWh"
        state: "{{ states('sensor.daily_pv1_inverter1_sum') | float + states('sensor.daily_pv2_inverter1_sum') | float }}"
      - name: "Inverter 2 Solar Power Daily"
        unit_of_measurement: "kWh"
        state: "{{ states('sensor.daily_pv1_inverter2_sum') | float + states('sensor.daily_pv2_inverter2_sum') | float }}"
      - name: "Inverter 3 Solar Power Daily"
        unit_of_measurement: "kWh"
        state: "{{ states('sensor.daily_pv1_inverter3_sum') | float + states('sensor.daily_pv2_inverter3_sum') | float }}"
 
      - name: "Inverter 1 Solar Power Now"
        unit_of_measurement: "kW"
        state: "{{ states('sensor.inverter1_pv1_power') | float + states('sensor.inverter1_pv2_power') | float }}"
      - name: "Inverter 2 Solar Power Now"
        unit_of_measurement: "kW"
        state: "{{ states('sensor.inverter2_pv1_power') | float + states('sensor.inverter2_pv2_power') | float }}"
      - name: "Inverter 3 Solar Power Now"
        unit_of_measurement: "kW"
        state: "{{ states('sensor.inverter3_pv1_power') | float + states('sensor.inverter3_pv2_power') | float }}"

```

**Comment by Phoenix17785** [comment]
Hi,

So for Inverter1 Name it seems to be sensor.h3_10_0_inverter
For Inverter2 name  it seems to be sensor.h3_10_0_inverter2
anf for Inverter3 name it seems to be sensor.h3_8_0_inverter

![image](https://github.com/macxq/foxess-ha/assets/155656072/2092bbd4-a664-4a33-ae7a-c02195637916)


![image](https://github.com/macxq/foxess-ha/assets/155656072/9ab9321b-8138-4361-9f88-978e6c49c721)

still searching for PV1 and PV2 String Names. 
As soon as I found them I should be able to follow your code above. 

Update:

found them 

Both H3 10 Inverters

sensor.h3_10_0_pv1_power
sensor.h3_10_0_pv1_power_2

sensor.h3_10_0_pv2_power
sensor.h3_10_0_pv2_power_2

sensor.h3_10_0_pv3_power
sensor.h3_10_0_pv3_power_2

sensor.h3_10_0_pv4_power
sensor.h3_10_0_pv4_power_2

I found until PV Power 4

does that mean they both have 2 strings per each inverter? 

the H3 8 Inverter

sensor.h3_8_0_pv1_power
sensor.h3_8_0_pv2_power

I found for the H3 8 Inverter until PV4 does that mean it has 4 strings? 


Again Thank you.

**Reply by FozzieUK** [reply]
All H3 inverters support only 2 PV strings, the integration however supports up to 4 - in this case 3 & 4 are not used and the state will be 'unknown'

From the image above your inverters are named as 'h3_8_0', 'h3_10_0' and 'h3_10_0' i.e. you have 2 inverters named h3_10_0, so what the integration then does is because each entity name has to be unique it adds a suffix _2 to the end of all of the second h3_10_0 inverters entities.

that means that for pv1 on the H3 inverter it will be called 'sensor.h3_8_0_pv1_power' and pv2 will be 'sensor.h3_8_0_pv2_power'

Your first h3_10_0 will be 'sensor.h10_8_0_pv1_power' and pv2 will be 'sensor.h10_8_0_pv2_power'

and your second h3_10_0 inverter will be 'sensor.h10_8_0_pv1_power_2' and pv2 will be 'sensor.h10_8_0_pv2_power_2'

So if I got that right, your code to be added to your configuration.yaml will be -

```
# Setup Better Solar Tracking Sensors that resolve negative solar tracking  

  - platform: integration
    source: sensor.h3_8_0_pv1_power
    name: h3_8_0_pv1_sum
    unit_time: h
    round: 2
  - platform: integration
    source: sensor.h3_10_0_pv1_power
    name: h3_10_0_pv1_sum
    unit_time: h
    round: 2
  - platform: integration
    source: sensor.h3_10_0_pv1_power_2
    name: h3_10_0_2_pv1_sum
    unit_time: h
    round: 2

  - platform: integration
    source: sensor.h3_8_0_pv2_power
    name: h3_8_0_pv2_sum
    unit_time: h
    round: 2
  - platform: integration
    source: sensor.h3_10_0_pv2_power
    name: h3_10_0_pv2_sum
    unit_time: h
    round: 2
  - platform: integration
    source: sensor.h3_10_0_pv2_power_2
    name: h3_10_0_2_pv2_sum
    unit_time: h
    round: 2

    
# Setup Daily and real-time solar trackers that resolve the negative solar tracking    

utility_meter:
    daily_h3_8_0_pv1_sum:
        source: sensor.h3_8_0_pv1_sum
        cycle: daily
    daily_h3_10_0_pv1_sum:
        source: h3_10_0_pv1_sum
        cycle: daily
    daily_h3_10_0_2_pv1_sum:
        source: h3_10_0_2_pv1_sum
        cycle: daily
 
    daily_h3_8_0_pv2_sum:
        source: sensor.h3_8_0_pv2_sum
        cycle: daily
    daily_h3_10_0_pv2_sum:
        source: sensor.h3_10_0_pv2_sum
        cycle: daily
    daily_h3_10_0_2_pv2_sum:
        source: sensor.h3_10_0_2_pv2_sum
        cycle: daily

# Setup Daily and real-time solar trackers that resolve the negative solar tracking   
       
template:
  - sensor:
      - name: "h3_8_0 Solar Power Daily"
        unit_of_measurement: "kWh"
        state: "{{ states('sensor.daily_h3_8_0_pv1_sum') | float + states('sensor.daily_h3_8_0_pv2_sum') | float }}"
      - name: "h3_10_0 Solar Power Daily"
        unit_of_measurement: "kWh"
        state: "{{ states('sensor.daily_h3_10_0_pv1_sum') | float + states('sensor.daily_h3_10_0_pv2_sum') | float }}"
      - name: "h3_10_0 Solar Power Daily 2"
        unit_of_measurement: "kWh"
        state: "{{ states('sensor.daily_h3_10_0_2_pv1_sum') | float + states('sensor.daily_h3_10_0_2_pv2_sum') | float }}"
 
      - name: "Inverter 1 Solar Power Now"
        unit_of_measurement: "kW"
        state: "{{ states('sensor.h3_8_0_pv1_power') | float + states('sensor.h3_8_0_pv2_power') | float }}"
      - name: "Inverter 2 Solar Power Now"
        unit_of_measurement: "kW"
        state: "{{ states('sensor.h3_10_0_pv1_power') | float + states('sensor.h3_10_0_pv2_power') | float }}"
      - name: "Inverter 3 Solar Power Now"
        unit_of_measurement: "kW"
        state: "{{ states('sensor.h3_10_0_pv1_power_2') | float + states('sensor.h3_10_0_pv2_power_2') | float }}"
```

Once that code has been added to your configuration.yaml you will have to restart HA again as the utility meters are only setup at startup

**Reply by Phoenix17785** [reply]
Thanks for your help. Put in the code, restarted HA .. one minor error? 

![Bildschirmfoto 2024-02-16 um 09 06 44](https://github.com/macxq/foxess-ha/assets/155656072/68a1d8bd-63fe-41f8-b103-f20650cbb5ce)

![Bildschirmfoto 2024-02-16 um 09 06 55](https://github.com/macxq/foxess-ha/assets/155656072/f05910d9-356f-41a6-8501-da866ac9ca78)

I can at any time change the name of the inverters and of course let the name change flow into this code ... correct? 

Thinking about naming the Inverters like ( sorry for german ) Wechselrichter links , Wechselrichter Mitte, Wechselrichter rechts. 
Other idea would be Master, Slave, and Standalone. As two of the inverters run Master & Slave and the third is independant to that Master & Slave pair.

**Reply by FozzieUK** [reply]
ahh ok, yes spotted it straight away 

the bit that says

```
utility_meter:
    daily_h3_8_0_pv1_sum:
        source: sensor.h3_8_0_pv1_sum
        cycle: daily
    daily_h3_10_0_pv1_sum:
        source: h3_10_0_pv1_sum
        cycle: daily
    daily_h3_10_0_2_pv1_sum:
        source: h3_10_0_2_pv1_sum
        cycle: daily
```

needs to be replaced by this

```
utility_meter:
    daily_h3_8_0_pv1_sum:
        source: sensor.h3_8_0_pv1_sum
        cycle: daily
    daily_h3_10_0_pv1_sum:
        source: sensor.h3_10_0_pv1_sum
        cycle: daily
    daily_h3_10_0_2_pv1_sum:
        source: sensor.h3_10_0_2_pv1_sum
        cycle: daily
```
(and then restart HA)

I missed 'sensor.' in the 2nd & 3rd utility meter 😒 

On the renaming, yes you can change the name at any time and the friendly name will change immediately, but because the integration entities have already been created the sensor.entity_name will stay as they are now. 

Just for information each entity has a friendly_name and an entity_name so your friendly name would be 'Wechselrichter links (entity)' whereas the entity name would still be sensor.H3_8_0_(entity).

Whenever you select an entity in the visual editor in a card or the dashboard it searches and displays the friendly name so it will all look as you want it to - you'll just have to remember if you ever code by hand that the entities will be called the 'old' names.

**Reply by Phoenix17785** [reply]
Thanks. 

Says this error now after restart ... but seems to work 

![Bildschirmfoto 2024-02-16 um 10 32 54](https://github.com/macxq/foxess-ha/assets/155656072/90413c6e-1e75-4a34-95ab-7ffa474cfb54)

![Bildschirmfoto 2024-02-16 um 10 34 58](https://github.com/macxq/foxess-ha/assets/155656072/5e392d2d-07b7-49e6-9456-794060f2a307)


![Bildschirmfoto 2024-02-16 um 10 33 36](https://github.com/macxq/foxess-ha/assets/155656072/62329f3b-f872-4a21-a4fb-996b552da8c6)

Does a backup of HA also include the configuration.yaml file from HACS? 

Don't want to loose the progress. 

Again Thank you for helping out.

**Reply by Daibutt** [reply]
The error may be due to a template syntax change a while back (but after the sensor code above was published). 
I think it is recommended (?) to have a default value for sensors in the value template.
An example here where "float" is changed to float(default=0);

```
  sensors:
    pv_total_daily:
      friendly_name: "Daily sum of PV1 + PV2"
      value_template: "{{ (states('sensor.daily_pv1_sum') | float(default=0) + states('sensor.daily_pv2_sum') | float(default=0)) | round(2) }}"
      unit_of_measurement: "kWh"
```
