### DISCUSSION TITLE
DeviceID installation before 2024

### DISCUSSION THREAD

**Discussion by horstvogel** [macxq/foxess-ha#254] [General]
Hello, where I cloud found the deviceID fore a installation before 2024? 
Thanks

```
sensor:
  - platform: foxess
    deviceID: enter_your_inverter_serial_number     -->??
    deviceSN: enter_your_inverter_serial_number
    apiKey: enter_your_personal_api_key
```
