### DISCUSSION TITLE
Rounding figures to a decimal place?

### DISCUSSION THREAD

**Discussion by Captain0Kangaroo** [macxq/foxess-ha#26] [General]
Does anyone know if it's possible to round some of the figures. 

For example currently i'm seeing Solar Generation of 1.54510kw and ideally it would be nice to just see 1.5kw. 
Same for many of the the other stats like 'Load Power' which shows 2.952kw where as 2.9kw would be fine.

?

Thanks

**Comment by amamoh** [comment]
Generated power is also very annoying, it looks like 6,09999999999999997 kWh.
How to round it up for 6,1 fox example?

**Reply by vicdavery** [reply]
You can do something like this in your configuration.yaml (or included files)
```
template:
  - sensor: 
    - name: "Generated"
      unit_of_measurement: "kWh"
      state:  "{{ states("sensor.foxess_energy_generated") | round(2) }}"
```
