### ISSUE TITLE
Double FoxESS household

### ISSUE THREAD

**Issue by williamjeccles** [macxq/foxess-ha#11]
Hi @macxq / @Daibutt,

First things first, I'm using this plugin with great success, I'm extremely pleased with it and your work. So a massive thank you!
If you could add a donate button to the readme I'd love to send you some money for your effort and time.

I've ordered my second FoxESS system but this time instead of solar I'm going to be using it for purely additional battery storage as I've maxed out my current system with 8 x HV2600 giving me a total 20.8kWh @ 450v.

Any ideas on how I would go about duplicating this plugin so that I can install it twice and target different deviceids?

I was thinking of forking it and changing the platform name to foxess2 and then namespacing every sensor but if you had any ideas I'd be interested. With the rising electric costs, charging overnight at cheaper rates is going to be normal and 20.8kWh isn't enough for me now that I've switched over to heat pumps from gas heating during the winter. During summer my 6kWh system will give me near zero grid use.

**Comment by Daibutt** [comment]
Hi @williamjeccles,

I'm afraid I'm going to have to defer to @macxq here, as he is the expert 👍 .
I am just a keen FoxESS owner with HA who kept bugging him by asking for additional features :) 
I like the sound of your proposed setup! (have PM'd you on LinkedIn).

**Comment by macxq** [comment]
Hi @williamjeccles!

Thank you for recognition for our work 🙇  it is a reward in itself 😄  
This integration has hidden feature that allows to configure multiple FoxESS devices :) but it was never tested :D

Try do add two FoxESS, distinguished by the name:

```
sensor:
  - platform: foxess
    name: FoxESS1
    username: foxesscloud_username
    password: foxesscloud_password
    deviceID: foxesscloud_inverter_id1
  - platform: foxess
    name: FoxESS2
    username: foxesscloud_username
    password: foxesscloud_password
    deviceID: foxesscloud_inverter_id2
```

and share the logs with me so i can fix it 😛
