### ISSUE TITLE
Sample Config with Solar Fixes

### ISSUE THREAD

**Issue by williamjeccles** [macxq/foxess-ha#12]
Adding my sample config which pulls together correct config, solar negatives fix, and a few extra bits that make FoxESS work way better for home assistant.

```
sensor:
  - platform: foxess
    username: foxesscloud_username
    password: foxesscloud_password
    deviceID: foxesscloud_inverter_id

# Setup Better Solar Tracking Sensors that resolve negative solar tracking  

  - platform: integration
    source: sensor.foxess_pv1_power
    name: pv1_sum
    unit_time: h
    round: 2
  - platform: integration
    source: sensor.foxess_pv2_power
    name: pv2_sum
    unit_time: h
    round: 2
    
# Setup Daily and real-time solar trackers that resolve the negative solar tracking    

utility_meter:
    daily_pv1_sum:
        source: sensor.pv1_sum
        cycle: daily
 
    daily_pv2_sum:
        source: sensor.pv2_sum
        cycle: daily
        
# Setup Daily and real-time solar trackers that resolve the negative solar tracking   
       
template:
  - sensor:
      - name: "Solar Power Daily"
        unit_of_measurement: "kWh"
        state: "{{ states('sensor.daily_pv1_sum') | float + states('sensor.daily_pv2_sum') | float }}"
 
      - name: "Solar Power Now"
        unit_of_measurement: "kW"
        state: "{{ states('sensor.foxess_pv1_power') | float + states('sensor.foxess_pv2_power') | float }}"
```
