### ISSUE TITLE
Help with install 

### ISSUE THREAD

**Issue by chesterflaps** [macxq/foxess-ha#192]
hi all.

I have just had my Growatt inverters replaced with the Fox ESS ones and I am wanting to integrate in to HA.

I have downloaded the HACS integration and I have not managed to get any further. It says 'manual installation' in the documentation which would suggest to me there is also an automatic installation which is what I thought would happen once I downloaded it but I guess not.

I have 2 inverters so I have added below code (obviously not with ****) to my main home assistant config yaml but not sure where I go from here to find the information.

```
sensor:
  - platform: foxess
    name: FoxESS1
    username: *****
    password: ******
    deviceID: 59e48e7c-95ff-47c8-ae4a-*********
  - platform: foxess
    name: FoxESS2
    username: *******
    password: ******
    deviceID: b9d1760b-6869-4027-a241-********
```
