### ISSUE TITLE
Unexpected Device Class

### ISSUE THREAD

**Issue by Sivivatu** [macxq/foxess-ha#238]
**Describe the bug**
In my Energy Dashboard configuration I am getting the error:
```yaml
Unexpected device class
The following entities do not have the expected device class:
sensor.foxess_pv1_sum
```

This means my energy dashboard is not showing any solar production.

My yaml config for the integration is below and the devices used on the energy dashboard are the integration platform sensors:

```yaml
  - platform: integration
    source: sensor.foxess_pv1_power
    name: foxess_pv1_sum
    unit_time: h
    round: 2
  - platform: integration
    source: sensor.foxess_pv2_power
    name: foxess_pv2_sum
    unit_time: h
    round: 2

# Setup Daily and Realtime solar trackers that resolve the negative solar tracking
utility_meter:
  daily_pv1_sum:
    source: sensor.foxess_pv1_sum
    cycle: daily
  daily_pv2_sum:
    source: sensor.foxess_pv2_sum
    cycle: daily

# Setup Daily and real-time solar trackers that resolve the negative solar tracking
template:
  - sensor:
      - name: "Solar Power Daily"
        unit_of_measurement: "kWh"
        state: "{{ states('sensor.daily_pv1_sum') | float }}"
        # device_class: power

      - name: "Solar Power Now"
        unit_of_measurement: "kW"
        state: "{{ states('sensor.foxess_pv1_power') | float }}"
        # device_class: power
```

**Expected behavior**
The integrated sums should (and were previously) populate the solar production dashboards

**Screenshots**
![image](https://github.com/macxq/foxess-ha/assets/7496456/53f8002a-3689-49c6-834d-863c4ab7c3d0)

**Debug logs:**

**HA version:**
Core
2024.4.3
Supervisor
2024.04.0
Operating System
12.2
Frontend
20240404.2

**foxess-ha version:**
v0.39
