### ISSUE TITLE
I don't see the panel information in dashboard

### ISSUE THREAD

**Issue by cmarco884** [macxq/foxess-ha#249]
I installed HA a few days ago. I followed the guide step by step to install this integration for FOXESS inverters but I don't see the inverter panel in the dashboard. Perhaps the way to search for the ID in foxesscloud has changed, it is now different from what is reported in the guide.

HA version: 2024.5.2

foxess-ha version: v0.40

**Comment by FozzieUK** [comment]
Hi, thanks for posting, yes it looks like Fox have changed the parameters that the website passes so it’s not in the same format as the original guide.

The inverter_id was used with legacy versions of this integration as part of the login process, but this new version uses the apiKey which means the inverter device id isn’t used anymore as part of the login process.

The only pre-requisite for the latest version is the inverter_id must be unique as it is used as the unique id for each entity so instead you can use your inverter serial number for the inverter_id as well as the inverter serial number and it will work fine.

i.e. it would look something like -

```
sensor:
  - platform: foxess
    deviceID: enter_your_inverter_serial_number
    deviceSN: enter_your_inverter_serial_number
    apiKey: enter_your_personal_api_key

```

I will modify the documentation and update it for new installations that use the openAPI.
