### ISSUE TITLE
Error in the evening

### ISSUE THREAD

**Issue by 4noxx** [macxq/foxess-ha#251]
i added this addon. works fine on day (with sun).

but in the evening lovelace shows errors....

![image](https://github.com/macxq/foxess-ha/assets/12627059/168fa2b4-f2a0-4af6-9b33-64fc0bef55d4)

Die Entität ist nicht-numerisch 
entity isnt numeric

1. FoxESS - FeedIn Power
2. FoxESS - Energy Generated

**Comment by FozzieUK** [comment]
Which inverter is it ?

If it’s a solar only inverter the datalogger will go off-line once the sun goes down, the `sensor.foxess_inverter` will show the inverter status as ‘off-line’ and all the entities will show ‘unknown’ as there is no state being reported.

**Comment by 4noxx** [comment]
Inverter: T10-G3

but everything is there in the cloud. why can't i use this data?

![image](https://github.com/macxq/foxess-ha/assets/12627059/f8233371-acb0-45c6-87ca-0f5e224b2c44)

**Comment by FozzieUK** [comment]
If there is feed in power showing in the cloud then you would expect the inverter to be on-line and it should be showing the same information as the cloud - the Fox OpenAPI has been having some problems (Fox are aware and are working on the problem) so it could be that is causing that problem.

*But* if the inverter goes into standby overnight, it shuts down the datalogger and the cloud will show it as off-line, when this happens there are no values being returned and so all the sensors become ‘unknown’ - you can click on them and they will still show their history. As soon as the inverter returns on-line it will start sending data and the sensors will start to show the most recent data. 

For the energy_generated sensor you can handle this by creating a utility meter and use the energy_generated sensor as it’s source. The utility meter will retain the value even when the energy_generated sensor goes off-line, that’s why utility meters are often used for long term statistics.

The yaml code for your configuration would look something like this-

```
utility_meter:
  generated_energy:
    source: sensor.foxess_energy_generated_2
    cycle: daily
    always_available: true

```

Most HA cards can deal with ‘unknown’ or ‘unavailable’ states, but if they cannot you can use templates to create ‘filtered’ sensors that deal with it to return a ‘known’ numeric state, like this-

```
template:
  - sensor:
      - name: "Filtered Feed In Power"
        unit_of_measurement: "kW"
        device_class: power
        state: "{{ states('sensor.foxess_feedin') if states('sensor.foxess_feedin')|is_number else 0 }}"

```
