### ISSUE TITLE
Error fetching FoxESS data: 41809

### ISSUE THREAD

**Issue by precz** [macxq/foxess-ha#57]
Hi, I got this issue and I'm not sure how to solve this:
```
Ten błąd pochodzi z niestandardowej integracji.

Logger: custom_components.foxess.sensor
Source: helpers/update_coordinator.py:219 
Integration: foxess (documentation, issues) 
First occurred: 21:04:58 (1 occurrences) 
Last logged: 21:04:58

Error fetching FoxESS data: Unable to get data from FoxESS: {"errno":41809,"result":null}
```

**Comment by macxq** [comment]
which version are you using?

**Comment by precz** [comment]
v0.14.4

**Comment by macxq** [comment]
please upgrade to v0.15

**Comment by macxq** [comment]
@precz does it still occurs ?

**Comment by precz** [comment]
Hi, sorry for my late response.  
My configuration was wrong. I had strings put between `"` quotes, like: 
```
sensor:
  - platform: "foxess"
    username: "foxesscloud_username"
    password: "foxesscloud_password"
    deviceID: "foxesscloud_inverter_id"
```
 Removed them and now it works!

Thanks for help, 
Best!
